### ISSUE TITLE
Explore kwok

### ISSUE THREAD

**Issue by howardjohn** [howardjohn/pilot-load#9]
https://github.com/kubernetes-sigs/kwok

might allow us to remove a lot of our logic

**Comment by wzshiming** [comment]
Hi, I've created a demo (https://github.com/wzshiming/pwod) that fully simulates istio testing based on this project and kwok, and I'd like to get your opinion on it.

It seems to me that this could be a very versatile istio test component, and adding it to istio org might be the better way to go.

Looking forward to your reply. 😄

PS: This is the part I realized I was missing when I wrote about testing istio with kwok https://github.com/istio/istio.io/pull/13588.
